### PR TITLE
Make host and port configurable

### PR DESCRIPTION
**Pull request by setzer22**
I wanted to test the results by serving them to another machine in my local network, but I realize this tool is hard-coded to listen at localhost, so I made these changes to make it configurable, keeping the old defaults.

This adds two new `--host` and `--port` command line flags, which are by default still "localhost" and "8000" respectively.

### CODE REVIEW

**Comment by rukai** [comment]
Looks good!
Just need to run `cargo fmt`

**Comment by setzer22** [comment]
@rukai Just pushed that cargo fmt :smile:

**Comment by rukai** [comment]
next up is a failing clippy lint

**Comment by setzer22** [comment]
Oops, sorry about that :facepalm:

**Comment by rukai** [comment]
Perfect, thanks!
I tested the new feature locally and works great.

**Pull request merged**
