### PR TITLE
Add support for custom HTML templates

### LINKED ISSUE #3: Custom Html
Appreciate your work on this project! 

However, I'm not a big fan of the h1 tag showing the name of the project.
I don't think people need to see their project name as h1 and there doesn't seem to be an option to remove it.

```
  <h1>{{name}}</h1>
```

I think there should be a way to provide your custom index.template.html
https://github.com/rukai/cargo-run-wasm/blob/main/src/index.template.html

### PR DESCRIPTION
**Pull request by parasyte**
- Fixes #3

### CODE REVIEW

**Comment by rukai** [comment]
From looking at https://github.com/parasyte/pixels/pull/310/files it seems like you (and everyone else who requested this feature) really want the default template to just set the canvas to take up the entire webpage.

I'm going to experiment with an approach I'm thinking of that will provide this, and will report back either today or tomorrow.
In the mean time I'd like to keep your PR open in case I decide that a user provided template was best after all.

**Comment by rukai** [comment]
I'm currently leaning towards just changing the template to `body { margin: 0; }` and removing the `<h1></h1>`
Can you explain what your use case of `body { overflow: hidden }` and `body { background-color: #000 }` is and if you could or couldnt live without them?

I would like to avoid exposing a complete template to the user to avoid having to document and commit to the format it must be in.

As a compromise I could also have a `css` arg that I inject into the `<style></style>`?
But the user could more robustly do this themselves with wasm-bindgen...

**Comment by parasyte** [comment]
Both of those CSS rules are specific to my application. `overflow: hidden` is used to hide the scrollbar that sometimes appears when an element is given the same size as the window viewport (without body margins). The black background matches the default clear color for the renderer.

I'm not strictly opposed to being locked in to one-template-fits-all, since practically any changes to the DOM can be made at runtime from Rust. But the convenience of an override seems like a big advantage over that alternative. Personally I don't do a whole lot of web app dev with Rust, so it's hard for me to claim that either way is objectively superior.

**Comment by rukai** [comment]
I've settled on another approach so I'll go ahead and close this.
Thanks for pushing this forwards!

**Pull request closed without merging**
