### PR TITLE
Refactor for Builder Pattern and Add custom HTML option

### LINKED ISSUE #35: add support for specifying html
Winit developers have brought up the desire to provide a full HTML file to cargo-run-wasm.
They want this as they need to provide a "javascript user" focused example, so having to use web_sys to write the html/javascript is no good.
See https://github.com/rust-windowing/winit/issues/2816 and https://github.com/rust-windowing/winit/pull/2852

I think its pretty clear that we need this feature, but I'm not sure yet how it should be designed.

Some competing ideas:
* turn [run_wasm_with_css](https://docs.rs/cargo-run-wasm/latest/cargo_run_wasm/fn.run_wasm_with_css.html#) into a builder struct that can also set the html body 
* Introduce a separate run_wasm_with_html_body function that inserts an html body into the html file
* Introduce a separate run_wasm_with_html function that takes a full html file and performs some templating on it to insert the wasm script.

### PR DESCRIPTION
**Pull request by stevenhuyn**
**Todo**
- [ ] Complete documentation

Closes #35
Makes Possible https://github.com/rust-windowing/winit/issues/2816
Will Enable https://github.com/rust-windowing/winit/pull/2852

Happy to change stuff, please feel free to suggest stuff.

```rust
fn main() {
    cargo_run_wasm::WasmRunnerBuilder::new()
        .css(
            r#"
        body { 
            margin: 0px; 
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        "#,
        )
        .html(include_str!("../../examples/web.html"))
        .build()
        .unwrap()
        .run();
}
``

### CODE REVIEW

**Comment by daxpedda** [comment]
Are two separate types really necessary? The `build()` function seems pretty useless:
```rust
WasmRunner::new().with_html(...).with_css(...).run();
```
... seems to do the trick.


EDIT: Just an idea, you should probably wait for @rukai's opinion on this.

**Comment by stevenhuyn** [comment]
Mr GPT suggested 2 structs but you make good points.

**Comment by rukai** [comment]
First a builder will be introduced as per https://github.com/rukai/cargo-run-wasm/pull/37#issuecomment-1627605512
Then I will come back to this PR and consider how we could introduce custom html into that builder.

**Comment by stevenhuyn** [comment]
legend, thanks man

**Pull request closed without merging**
